<?php

/**
 * @file
 * Contains commerce_lightning.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_lightning_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_lightning module.
    case 'help.page.commerce_lightning':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Makes lightning(LND) payments available via Commerce.') . '</p>';
      return $output;

    default:
  }
}
